"""Context-Free Grammar (CFG) model."""

from collections import deque


class CFG:
    def __init__(self):
        self.variables = set()
        self.terminals = set()
        self.productions = {}  # variable -> list of productions (each is a string)
        self.start_symbol = None

    @staticmethod
    def parse(text):
        """Parse text definition into a CFG. Returns (CFG, errors)."""
        cfg = CFG()
        lines = text.strip().split('\n')
        errors = []
        first_variable = None

        for line in lines:
            line = line.split('#')[0].strip()
            if not line:
                continue

            lower = line.lower()
            if lower.startswith('start:') or lower.startswith('inicio:'):
                cfg.start_symbol = line.split(':', 1)[1].strip()
                continue
            if lower.startswith('variables:'):
                cfg.variables = {s.strip() for s in line.split(':', 1)[1].split(',') if s.strip()}
                continue
            if lower.startswith('terminals:') or lower.startswith('terminales:'):
                cfg.terminals = {s.strip() for s in line.split(':', 1)[1].split(',') if s.strip()}
                continue

            # Parse production rule: A -> alpha | beta | gamma
            if '->' in line:
                left, right = line.split('->', 1)
                variable = left.strip()
                if first_variable is None:
                    first_variable = variable
                cfg.variables.add(variable)

                alternatives = [alt.strip() for alt in right.split('|')]
                if variable not in cfg.productions:
                    cfg.productions[variable] = []
                for alt in alternatives:
                    if alt:
                        cfg.productions[variable].append(alt)
                        # Auto-detect terminals
                        for ch in alt.split():
                            if ch and not ch[0].isupper() and ch != 'ε' and ch != 'eps':
                                cfg.terminals.add(ch)
                        # Also check for single-char terminals in compact notation
                        if not any(c == ' ' for c in alt):
                            for ch in alt:
                                if ch.islower() or (not ch.isalpha() and ch not in 'ε'):
                                    cfg.terminals.add(ch)

        if cfg.start_symbol is None:
            cfg.start_symbol = first_variable

        if not cfg.productions:
            errors.append("No se definieron producciones")
        if cfg.start_symbol is None:
            errors.append("No se definio simbolo inicial")
        elif cfg.start_symbol not in cfg.productions:
            errors.append(f"Simbolo inicial '{cfg.start_symbol}' no tiene producciones")

        if errors:
            return None, errors
        return cfg, []

    def _is_variable(self, symbol):
        """Check if a symbol is a variable (uppercase start)."""
        return symbol in self.variables or (len(symbol) > 0 and symbol[0].isupper())

    def _tokenize(self, production):
        """Split production into tokens. Handles both 'a B c' and 'aBc' notations."""
        if ' ' in production:
            return production.split()
        # Single char tokenization
        tokens = []
        i = 0
        while i < len(production):
            if production[i] == 'ε':
                tokens.append('ε')
                i += 1
            else:
                tokens.append(production[i])
                i += 1
        return tokens

    def _sentential_to_string(self, tokens):
        """Convert token list to a display string (no spaces for compact, spaces for spaced)."""
        filtered = [t for t in tokens if t not in ('ε', 'eps')]
        if not filtered:
            return 'ε'
        return ''.join(filtered)

    def test(self, input_string, max_steps=5000):
        """Test if string is generated by the grammar using BFS derivation.
        Returns (accepted, derivation_steps, message).
        """
        if not input_string and any('ε' in p or 'eps' in p
                                     for prods in self.productions.values()
                                     for p in prods):
            # Check if start can derive epsilon
            for prod in self.productions.get(self.start_symbol, []):
                if prod in ('ε', 'eps'):
                    return True, [self.start_symbol, 'ε'], "ACEPTADA"

        if not input_string:
            input_string = 'ε'

        target = input_string if input_string != 'ε' else ''

        # BFS derivation
        queue = deque()
        queue.append((self.start_symbol, [self.start_symbol]))
        visited = set()
        visited.add(self.start_symbol)
        steps = 0

        while queue and steps < max_steps:
            steps += 1
            current, derivation = queue.popleft()

            # Tokenize current sentential form
            tokens = self._tokenize(current)

            # Find leftmost variable
            var_idx = None
            for i, token in enumerate(tokens):
                if self._is_variable(token):
                    var_idx = i
                    break

            if var_idx is None:
                # No variables left - check if matches target
                result = ''.join(t for t in tokens if t not in ('ε', 'eps'))
                if result == target:
                    return True, derivation, "ACEPTADA"
                continue

            variable = tokens[var_idx]
            for prod in self.productions.get(variable, []):
                prod_tokens = self._tokenize(prod)
                new_tokens = tokens[:var_idx] + prod_tokens + tokens[var_idx + 1:]
                new_form = ''.join(t for t in new_tokens if t not in ('ε', 'eps'))

                # Prune: if terminal prefix doesn't match, skip
                terminal_prefix = ''
                for t in new_tokens:
                    if self._is_variable(t):
                        break
                    if t not in ('ε', 'eps'):
                        terminal_prefix += t
                if not target.startswith(terminal_prefix):
                    continue

                # Prune: if string without variables is longer than target, skip
                terminal_only = ''.join(t for t in new_tokens if not self._is_variable(t) and t not in ('ε', 'eps'))
                if len(terminal_only) > len(target):
                    continue

                new_str = ' '.join(new_tokens) if ' ' in current else ''.join(new_tokens)
                if new_str not in visited:
                    visited.add(new_str)
                    queue.append((new_str, derivation + [new_str]))

        if steps >= max_steps:
            return False, [], f"Limite de {max_steps} pasos alcanzado (la cadena puede ser muy larga o la gramatica es ambigua)"
        return False, [], "RECHAZADA (la cadena no es generada por la gramatica)"

    def leftmost_derivation(self, input_string, max_steps=5000):
        """Find a leftmost derivation for the string.
        Returns (found, derivation_steps, message).
        derivation_steps is list of (sentential_form_string, production_used) tuples.
        The first entry has production_used = None.
        """
        target = input_string if input_string else ''

        # Handle epsilon
        if not input_string or input_string == 'ε':
            target = ''
            for prod in self.productions.get(self.start_symbol, []):
                if prod in ('ε', 'eps'):
                    return True, [
                        (self.start_symbol, None),
                        ('ε', (self.start_symbol, prod))
                    ], "Derivacion encontrada"

        # BFS: state = (sentential_form_str, derivation_trail)
        # derivation_trail: list of (display_string, production_or_None)
        start_state = self.start_symbol
        queue = deque()
        queue.append((start_state, [(self.start_symbol, None)]))
        visited = {start_state}
        steps = 0

        while queue and steps < max_steps:
            steps += 1
            current, trail = queue.popleft()
            tokens = self._tokenize(current)

            # Find leftmost variable
            var_idx = None
            for i, token in enumerate(tokens):
                if self._is_variable(token):
                    var_idx = i
                    break

            if var_idx is None:
                result = ''.join(t for t in tokens if t not in ('ε', 'eps'))
                if result == target:
                    return True, trail, "Derivacion encontrada"
                continue

            variable = tokens[var_idx]
            for prod in self.productions.get(variable, []):
                prod_tokens = self._tokenize(prod)
                new_tokens = tokens[:var_idx] + prod_tokens + tokens[var_idx + 1:]

                # Prune
                terminal_prefix = ''
                for t in new_tokens:
                    if self._is_variable(t):
                        break
                    if t not in ('ε', 'eps'):
                        terminal_prefix += t
                if not target.startswith(terminal_prefix):
                    continue

                terminal_only = ''.join(t for t in new_tokens
                                        if not self._is_variable(t) and t not in ('ε', 'eps'))
                if len(terminal_only) > len(target):
                    continue

                new_str = ' '.join(new_tokens) if ' ' in current else ''.join(new_tokens)
                display = self._sentential_to_string(new_tokens)

                if new_str not in visited:
                    visited.add(new_str)
                    new_trail = trail + [(display, (variable, prod))]
                    queue.append((new_str, new_trail))

        if steps >= max_steps:
            return False, [], f"Limite de {max_steps} pasos alcanzado"
        return False, [], "No se encontro derivacion"

    def all_leftmost_derivations(self, input_string, max_count=10, max_steps=5000):
        """Find ALL leftmost derivations for a string (for ambiguity check).
        Returns list of derivations. Each derivation is a list of
        (sentential_form_string, (variable, production)) tuples.
        Two derivations differ if at any step a different production is applied.
        """
        target = input_string if input_string else ''

        if not input_string or input_string == 'ε':
            target = ''
            results = []
            for prod in self.productions.get(self.start_symbol, []):
                if prod in ('ε', 'eps'):
                    results.append([
                        (self.start_symbol, None),
                        ('ε', (self.start_symbol, prod))
                    ])
            return results

        # BFS but allow revisiting states reached via DIFFERENT production sequences.
        # Key: track the sequence of productions used (as a tuple) to avoid duplicates.
        # State: (sentential_form_str, production_sequence_tuple)
        results = []
        queue = deque()
        # (current_form, trail, prod_sequence_tuple)
        queue.append((self.start_symbol, [(self.start_symbol, None)], ()))
        seen_sequences = set()
        seen_sequences.add(())
        steps = 0

        while queue and steps < max_steps and len(results) < max_count:
            steps += 1
            current, trail, prod_seq = queue.popleft()
            tokens = self._tokenize(current)

            # Find leftmost variable
            var_idx = None
            for i, token in enumerate(tokens):
                if self._is_variable(token):
                    var_idx = i
                    break

            if var_idx is None:
                result = ''.join(t for t in tokens if t not in ('ε', 'eps'))
                if result == target:
                    results.append(trail)
                    if len(results) >= max_count:
                        break
                continue

            variable = tokens[var_idx]
            for prod_idx, prod in enumerate(self.productions.get(variable, [])):
                prod_tokens = self._tokenize(prod)
                new_tokens = tokens[:var_idx] + prod_tokens + tokens[var_idx + 1:]

                # Prune
                terminal_prefix = ''
                for t in new_tokens:
                    if self._is_variable(t):
                        break
                    if t not in ('ε', 'eps'):
                        terminal_prefix += t
                if not target.startswith(terminal_prefix):
                    continue

                terminal_only = ''.join(t for t in new_tokens
                                        if not self._is_variable(t) and t not in ('ε', 'eps'))
                if len(terminal_only) > len(target):
                    continue

                new_str = ' '.join(new_tokens) if ' ' in current else ''.join(new_tokens)
                display = self._sentential_to_string(new_tokens)
                new_prod_seq = prod_seq + ((variable, prod_idx),)

                if new_prod_seq not in seen_sequences:
                    seen_sequences.add(new_prod_seq)
                    new_trail = trail + [(display, (variable, prod))]
                    queue.append((new_str, new_trail, new_prod_seq))

        return results

    def is_ambiguous_for(self, input_string, max_steps=5000):
        """Check if a specific string has multiple leftmost derivations.
        Returns (is_ambiguous, derivations_found, message).
        """
        derivations = self.all_leftmost_derivations(input_string, max_count=2, max_steps=max_steps)
        if len(derivations) >= 2:
            return True, derivations, "La cadena es AMBIGUA: tiene multiples derivaciones por la izquierda"
        elif len(derivations) == 1:
            return False, derivations, "La cadena tiene una unica derivacion por la izquierda"
        else:
            return False, [], "No se encontro derivacion para esta cadena"

    def build_parse_tree(self, derivation):
        """Build a parse tree from a leftmost derivation.
        derivation: list of (display_string, (variable, production) or None).
        Returns tree structure: {'symbol': str, 'children': [tree_nodes]}
        Leaf nodes: {'symbol': str, 'children': []}
        """
        if not derivation or len(derivation) < 2:
            return None

        # The first entry is the start symbol
        root = {'symbol': self.start_symbol, 'children': []}

        # Collect the productions used in order
        productions_used = []
        for _, prod_info in derivation[1:]:
            if prod_info is not None:
                productions_used.append(prod_info)

        if not productions_used:
            return root

        # Apply each production to the tree by finding the leftmost variable leaf
        # and expanding it
        for variable, prod_str in productions_used:
            # Find the leftmost variable leaf in the tree
            leaf = self._find_leftmost_variable_leaf(root)
            if leaf is None:
                break

            # Expand this leaf with the production's RHS
            prod_tokens = self._tokenize(prod_str)
            if prod_tokens == ['ε'] or prod_tokens == ['eps']:
                leaf['children'] = [{'symbol': 'ε', 'children': []}]
            else:
                leaf['children'] = [{'symbol': t, 'children': []} for t in prod_tokens]

        return root

    def _find_leftmost_variable_leaf(self, node):
        """Find the leftmost variable node with no children (unexpanded)."""
        if not node['children'] and self._is_variable(node['symbol']):
            return node
        for child in node['children']:
            result = self._find_leftmost_variable_leaf(child)
            if result is not None:
                return result
        return None

    def generate_strings(self, max_length=8, max_count=20):
        """Generate strings in the language using BFS.
        Returns list of strings sorted by length.
        """
        results = set()
        queue = deque()
        queue.append(self.start_symbol)
        visited = set()
        visited.add(self.start_symbol)

        while queue and len(results) < max_count * 3:
            current = queue.popleft()
            tokens = self._tokenize(current)

            # Find leftmost variable
            var_idx = None
            for i, token in enumerate(tokens):
                if self._is_variable(token):
                    var_idx = i
                    break

            if var_idx is None:
                result = ''.join(t for t in tokens if t not in ('ε', 'eps'))
                if len(result) <= max_length:
                    results.add(result if result else 'ε')
                continue

            variable = tokens[var_idx]
            for prod in self.productions.get(variable, []):
                prod_tokens = self._tokenize(prod)
                new_tokens = tokens[:var_idx] + prod_tokens + tokens[var_idx + 1:]

                # Prune: if all terminals exceed max length, skip
                terminal_only = ''.join(t for t in new_tokens if not self._is_variable(t) and t not in ('ε', 'eps'))
                if len(terminal_only) > max_length:
                    continue

                new_str = ' '.join(new_tokens) if ' ' in current else ''.join(new_tokens)
                if new_str not in visited:
                    visited.add(new_str)
                    queue.append(new_str)

        sorted_results = sorted(results, key=lambda s: (len(s), s))
        return sorted_results[:max_count]

    def get_formatted_productions(self):
        """Return formatted production rules as string."""
        lines = []
        for var in sorted(self.productions.keys(),
                          key=lambda v: (v != self.start_symbol, v)):
            prods = ' | '.join(self.productions[var])
            lines.append(f"{var} -> {prods}")
        return '\n'.join(lines)

    @staticmethod
    def example():
        return "# CFG: Genera {0^n 1^n | n >= 0}\nS -> 0S1 | ε"

    @staticmethod
    def example2():
        return "# CFG: Expresiones aritmeticas (no ambigua)\nE -> E+T | T\nT -> T*F | F\nF -> (E) | a"

    @staticmethod
    def example3():
        return "# CFG: Expresiones aritmeticas (AMBIGUA)\nE -> E+E | E*E | (E) | a"
